pub const WEEK_TO_DAY: usize = 7;

pub const MINUTE_TO_SECONDS: u64 = 60;
pub const HOUR_TO_SECONDS: u64 = 60 * MINUTE_TO_SECONDS;
pub const DAY_TO_SECONDS: u64 = 24 * HOUR_TO_SECONDS;
pub const WEEK_TO_SECONDS: u64 = 7 * DAY_TO_SECONDS;
pub const MONTH_TO_SECONDS: u64 = 30 * WEEK_TO_SECONDS;
pub const YEAR_TO_SECONDS: u64 = 365 * MONTH_TO_SECONDS;

pub const YEAR_TO_DAYS: f32 = 365.25;
